### ISSUE TITLE
integrate with qutip mesolve ?

### ISSUE THREAD

**Issue by Papageno2** [echkon/tqix-developers#48]
Hi, An impressive repository for GPU utilization! 

I'm curious if this can seamlessly integrate with qutip. 
I see the paper [tqix.pis: A toolbox for quantum dynamics simulation of spin ensembles in Dicke basis](https://www.sciencedirect.com/science/article/abs/pii/S0010465523000310) with a section name "Appendix A: An example code for employing a
quantum circuit in qutip.pis", maybe `qutip` is a typo?

My goal is to perform dynamic simulations, specifically simulating the `open Dicke mode` in a driven-dissipation scenario. Could you provide guidance on how to achieve this?

thx.

**Comment by echkon** [comment]
Hello,

I appreciate your comment. There appears to be a typo with "qutip.pis." The correct term is "tqix.pis." 
For conducting dynamic simulations involving the open Dicke mode, you can utilize "qutip.piqs" from the Qutip library. For a detailed understanding of how we compute the dynamics of this Dicke model with modifications to "qutip.piqs," you can refer to Appendix B in this paper: https://journals.aps.org/pra/abstract/10.1103/PhysRevA.102.022602.

In our platform, "tqix," currently lacks the capability to perform such dynamic simulations. Presently, we employ Kraus operators for managing these dynamics, which are limited to full Hilbert-Space systems (2^N).

Best regards,
